services:
  fastapi-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi-baseline
    ports:
      - "8080:8080"
    environment:
      - TZ=UTC
      - REDIS_HOST=redis
      - REDIS_PORT=6380
    volumes:
      - ./logs:/app/logs
    depends_on:
      - redis
    env_file:
      - .env
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    ports:
      - "6380:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

volumes:
  redis_data:
