name: Deploy to Yandex Cloud

on:
  push:
    branches: [ main ]

env:
  CR_REGISTRY: cr.yandex
  CR_REPOSITORY: itmo-ai-bot
  IMAGE_TAG: ${{ github.sha }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    - name: Login to Yandex Cloud Container Registry
      id: login-cr
      uses: yc-actions/yc-cr-login@v1
      with:
        yc-sa-json-credentials: ${{ secrets.YC_SA_JSON }}

    - name: Build and Push Docker image
      env:
        CR_REPOSITORY: ${{ env.CR_REGISTRY }}/${{ secrets.YC_REGISTRY_ID }}/itmo-ai-bot
      run: |
        docker build -t $CR_REPOSITORY:$IMAGE_TAG -f Dockerfile.prod \
          --build-arg REDIS_HOST=${{ secrets.REDIS_HOST }} \
          --build-arg REDIS_PORT=${{ secrets.REDIS_PORT }} \
          --build-arg REDIS_PASSWORD=${{ secrets.REDIS_PASSWORD }} \
          --build-arg YANDEX_API_KEY=${{ secrets.YANDEX_API_KEY }} \
          --build-arg YANDEX_FOLDER_ID=${{ secrets.YANDEX_FOLDER_ID }} \
          --build-arg GOOGLE_API_KEY=${{ secrets.GOOGLE_API_KEY }} \
          --build-arg GOOGLE_CSE_ID=${{ secrets.GOOGLE_CSE_ID }} .
        docker push $CR_REPOSITORY:$IMAGE_TAG
        docker tag $CR_REPOSITORY:$IMAGE_TAG $CR_REPOSITORY:latest
        docker push $CR_REPOSITORY:latest

    - name: Deploy to Yandex Cloud Serverless Containers
      uses: yc-actions/yc-sls-container-deploy@v1
      with:
        yc-sa-json-credentials: ${{ secrets.YC_SA_JSON }}
        container-name: itmo-ai-bot
        folder-id: ${{ secrets.YC_FOLDER_ID }}
        revision-image-url: ${{ env.CR_REGISTRY }}/${{ secrets.YC_REGISTRY_ID }}/itmo-ai-bot:${{ github.sha }}
        revision-service-account-id: ${{ secrets.YC_SERVICE_ACCOUNT_ID }}
        revision-cores: 1
        revision-memory: 256MB
        revision-core-fraction: 100
        revision-concurrency: 16  # Максимально допустимое значение для Yandex Cloud
        revision-timeout: 90  # Увеличиваем таймаут до 90 секунд
        revision-env: |
          REDIS_HOST=${{ secrets.REDIS_HOST }}
          REDIS_PORT=${{ secrets.REDIS_PORT }}
          REDIS_PASSWORD=${{ secrets.REDIS_PASSWORD }}
          YANDEX_API_KEY=${{ secrets.YANDEX_API_KEY }}
          YANDEX_FOLDER_ID=${{ secrets.YANDEX_FOLDER_ID }}
          GOOGLE_API_KEY=${{ secrets.GOOGLE_API_KEY }}
          GOOGLE_CSE_ID=${{ secrets.GOOGLE_CSE_ID }}
